Update change_url script

diff --git a/scripts/change_url b/scripts/change_url
--- a/scripts/change_url
+++ b/scripts/change_url
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 #=================================================
 # GENERIC STARTING
@@ -27,12 +27,11 @@ app=$YNH_APP_INSTANCE_NAME
 ynh_script_progression --message="Loading installation settings..." --time --weight=1
 
 # Needed for helper "ynh_add_nginx_config"
-final_path=$(ynh_app_setting_get --app=$app --key=final_path)
+final_path=$(ynh_app_setting_get --app="$app" --key=final_path)
+is_public=$(ynh_app_setting_get --app="$app" --key=is_public)
+final_path=$(ynh_app_setting_get --app="$app" --key=final_path)
+port=$(ynh_app_setting_get --app="$app" --key=port)
 
-# Add settings here as needed by your application
-#db_name=$(ynh_app_setting_get --app=$app --key=db_name)
-#db_user=$db_name
-#db_pwd=$(ynh_app_setting_get --app=$app --key=db_pwd)
 
 #=================================================
 # BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
@@ -42,11 +41,11 @@ ynh_script_progression --message="Backing up the app before changing its url (ma
 # Backup the current version of the app
 ynh_backup_before_upgrade
 ynh_clean_setup () {
-	# Remove the new domain config file, the remove script won't do it as it doesn't know yet its location.
-	ynh_secure_remove --file="/etc/nginx/conf.d/$new_domain.d/$app.conf"
+    # Remove the new domain config file, the remove script won't do it as it doesn't know yet its location.
+    ynh_secure_remove --file="/etc/nginx/conf.d/$new_domain.d/$app.conf"
 
-	# restore it if the upgrade fails
-	ynh_restore_upgradebackup
+    # restore it if the upgrade fails
+    ynh_restore_upgradebackup
 }
 # Exit if an error occurs during the execution of the script
 ynh_abort_if_errors
@@ -56,15 +55,13 @@ ynh_abort_if_errors
 #=================================================
 
 change_domain=0
-if [ "$old_domain" != "$new_domain" ]
-then
-	change_domain=1
+if [ "$old_domain" != "$new_domain" ]; then
+    change_domain=1
 fi
 
 change_path=0
-if [ "$old_path" != "$new_path" ]
-then
-	change_path=1
+if [ "$old_path" != "$new_path" ]; then
+    change_path=1
 fi
 
 #=================================================
@@ -72,9 +69,9 @@ fi
 #=================================================
 # STOP SYSTEMD SERVICE
 #=================================================
-ynh_script_progression --message="Stopping a systemd service..." --time --weight=1
+ynh_script_progression --message="Stopping the systemd service..." --time --weight=1
 
-ynh_systemd_action --service_name=$app --action="stop" --log_path="/var/log/$app/$app.log"
+ynh_systemd_action --service_name="$app" --action="stop" --log_path="/var/log/$app/$app.log"
 
 #=================================================
 # MODIFY URL IN NGINX CONF
@@ -84,32 +81,61 @@ ynh_script_progression --message="Updating nginx web server configuration..." --
 nginx_conf_path=/etc/nginx/conf.d/$old_domain.d/$app.conf
 
 # Change the path in the nginx config file
-if [ $change_path -eq 1 ]
-then
-	# Make a backup of the original nginx config file if modified
-	ynh_backup_if_checksum_is_different --file="$nginx_conf_path"
-	# Set global variables for nginx helper
-	domain="$old_domain"
-	path_url="$new_path"
-	# Create a dedicated nginx config
-	ynh_add_nginx_config
+if [ $change_path -eq 1 ]; then
+    # Make a backup of the original nginx config file if modified
+    ynh_backup_if_checksum_is_different --file="$nginx_conf_path"
+    # Set global variables for nginx helper
+    domain="$old_domain"
+    path_url="$new_path"
+    # Create a dedicated nginx config
+    ynh_add_nginx_config
 fi
 
 # Change the domain for nginx
-if [ $change_domain -eq 1 ]
-then
-	# Delete file checksum for the old conf file location
-	ynh_delete_file_checksum --file="$nginx_conf_path"
-	mv $nginx_conf_path /etc/nginx/conf.d/$new_domain.d/$app.conf
-	# Store file checksum for the new config file location
-	ynh_store_file_checksum --file="/etc/nginx/conf.d/$new_domain.d/$app.conf"
+if [ $change_domain -eq 1 ]; then
+    # Delete file checksum for the old conf file location
+    ynh_delete_file_checksum --file="$nginx_conf_path"
+    mv "$nginx_conf_path" "/etc/nginx/conf.d/$new_domain.d/$app.conf"
+    # Store file checksum for the new config file location
+    ynh_store_file_checksum --file="/etc/nginx/conf.d/$new_domain.d/$app.conf"
 fi
 
 #=================================================
 # SPECIFIC MODIFICATIONS
 #=================================================
-# ...
+# BUILD YARN DEPENDENCIES
 #=================================================
+ynh_script_progression --message="Rebuilding yarn dependencies..." --weight=2
+
+chown -R "$app":"$app" "$final_path"
+
+pushd "$final_path" || return 1
+    ynh_use_nodejs
+    sudo -u "$app" env "$ynh_node_load_PATH" yarn global add wetty
+    yarn_bin_dir="$(sudo -u "$app" env "$ynh_node_load_PATH" yarn global bin)"
+popd || return 1
+
+#=================================================
+# SECURE FILES AND DIRECTORIES
+#=================================================
+
+# Set permissions to app files
+chown -R root: "$final_path"
+
+#=================================================
+# SETUP SYSTEMD
+#=================================================
+ynh_script_progression --message="Configuring the systemd service..." --weight=1
+
+domain="$new_domain"
+
+# Create a dedicated systemd config
+ynh_backup_if_checksum_is_different --file="/etc/systemd/system/$app.service"
+ynh_remove_systemd_config
+ynh_add_systemd_config --others_var="domain port path_url ynh_node_load_PATH yarn_bin_dir"
+ynh_store_file_checksum --file="/etc/systemd/system/$app.service"
+
+systemctl daemon-reload
 
 #=================================================
 # GENERIC FINALISATION
@@ -118,7 +144,7 @@ fi
 #=================================================
 ynh_script_progression --message="Starting a systemd service..." --time --weight=1
 
-ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app/$app.log"
+ynh_systemd_action --service_name="$app" --action="start" --log_path="/var/log/$app/$app.log"
 
 #=================================================
 # RELOAD NGINX
